# Generated by Django 5.0.4 on 2024-04-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaytacaApp', '0002_alter_merchants_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchants',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
