# Generated by Django 5.0.6 on 2024-05-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merchant_last_update_merchant_watchtower_merchant_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['-last_transaction_date']},
        ),
    ]
