# Generated by Django 5.0.6 on 2024-05-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_options_alter_merchant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='test_shop',
            field=models.BooleanField(default=False),
        ),
    ]
