# Generated by Django 5.0.6 on 2024-05-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merchant_test_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
