# Generated by Django 5.0.6 on 2024-09-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_location_province_location_state_location_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='receiving_address',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='receiving_pubkey',
        ),
    ]
