# Generated by Django 5.0.6 on 2024-10-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_merchant_receiving_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vault',
        ),
    ]
