# Generated by Django 5.0.6 on 2025-04-08 12:54

import django.db.models.deletion
from django.db import migrations, models


def migrate_categories(apps, schema_editor):
    Merchant = apps.get_model('main', 'Merchant')
    Category = apps.get_model('main', 'Category')
    
    # Get all unique non-empty categories from merchants
    unique_categories = set(
        merchant.category 
        for merchant in Merchant.objects.all() 
        if merchant.category
    )
    
    # Create Category objects and build a mapping
    category_map = {}
    for category_name in unique_categories:
        category = Category.objects.create(
            name=category_name,
            description=f'Category for {category_name}'
        )
        category_map[category_name] = category
    
    # Update all merchants with their new category relationships
    for merchant in Merchant.objects.all():
        if merchant.category:
            merchant.category_new = category_map[merchant.category]
            merchant.save()


def reverse_migrate_categories(apps, schema_editor):
    Merchant = apps.get_model('main', 'Merchant')
    Category = apps.get_model('main', 'Category')
    
    # Update all merchants to use the category name instead of the relationship
    for merchant in Merchant.objects.all():
        if merchant.category_new:
            merchant.category = merchant.category_new.name
            merchant.save()
    
    # Delete all Category objects
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_legacy_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='merchant',
            name='category_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
        migrations.RunPython(
            migrate_categories,
            reverse_migrate_categories
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='category',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='category_new',
            new_name='category',
        ),
    ]
