# Generated by Django 5.0.6 on 2025-04-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_merchant_city_alter_merchant_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='category',
        ),
        migrations.AddField(
            model_name='merchant',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main.category'),
        ),
    ]
