# Generated by Django 5.0.6 on 2025-04-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_merchant_options_category_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
