# Generated by Django 5.0.6 on 2025-04-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_merchant_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='logo_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
