# Generated by Django 4.2.27 on 2026-03-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_alter_merchant_logo_size_alter_merchant_logo_url"),
    ]

    operations = [
        migrations.RunSQL(
            # Create cache table (idempotent - won't fail if table exists)
            """
            CREATE TABLE IF NOT EXISTS cache_table (
                cache_key varchar(255) NOT NULL PRIMARY KEY,
                value text NOT NULL,
                expires bigint NOT NULL
            );
            """,
            # Reverse migration - drop table
            "DROP TABLE IF EXISTS cache_table;",
        ),
    ]
