# Generated by Django 4.2.27 on 2026-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_create_cache_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
