# Generated by Django 5.0.6 on 2026-09-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_merchant_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='nfc_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
