# Generated by Django 5.0.6 on 2026-09-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_merchant_nfc_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('x', 'X')], db_index=True, max_length=20)),
                ('link', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchants', models.ManyToManyField(blank=True, related_name='feed_posts', to='main.merchant')),
            ],
            options={
                'ordering': ['-posted_at', '-created_at'],
            },
        ),
    ]
