# Generated by Django 5.0.6 on 2026-09-27 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_feedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='posted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
    ]
