# Generated by Django 5.0.6 on 2026-09-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_feedpost_posted_at_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='image_url',
            field=models.URLField(blank=True, help_text='Preview image/thumbnail URL. Left blank, TikTok posts are auto-filled via oEmbed.', max_length=500, null=True),
        ),
    ]
