# Generated by Django 5.0.6 on 2026-09-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_feedpost_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a preview image. Takes precedence over the remote thumbnail URL.', null=True, upload_to='feed/'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='image_url',
            field=models.URLField(blank=True, help_text='Remote preview image URL. Left blank, TikTok posts are auto-filled via oEmbed.', max_length=500, null=True),
        ),
    ]
