# Generated by Django 5.0.4 on 2024-04-23 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gmap_business_link', models.URLField(blank=True, null=True)),
                ('last_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('receiving_pubkey', models.CharField(blank=True, max_length=255, null=True)),
                ('receiving_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=10, null=True)),
                ('url', models.URLField(null=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PaytacaApp.merchants')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PaytacaApp.merchants')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PaytacaApp.merchants')),
            ],
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255, null=True)),
                ('token_address', models.CharField(max_length=255, null=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PaytacaApp.merchants')),
            ],
        ),
    ]
