# Generated by Django 5.0.4 on 2024-04-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaytacaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchants',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
