# Generated by Django 5.0.3 on 2024-04-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaytacaApp', '0002_location_category_location_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gmap_business_link', models.URLField(blank=True, null=True)),
                ('last_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('receiving_pubkey', models.CharField(blank=True, max_length=255, null=True)),
                ('receiving_address', models.CharField(blank=True, max_length=255, null=True)),
                ('vault_id', models.IntegerField(blank=True, null=True)),
                ('voucher_total', models.IntegerField(default=0)),
                ('voucher_claimed', models.IntegerField(default=0)),
                ('voucher_unclaimed', models.IntegerField(default=0)),
                ('logo_30x30', models.URLField(blank=True, null=True)),
                ('logo_60x60', models.URLField(blank=True, null=True)),
                ('logo_90x90', models.URLField(blank=True, null=True)),
                ('logo_120x120', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
